
import Head from 'next/head'
import Image from "next/image";
import { useState } from 'react'
import style from '@/styles/home.module.scss'


export default function LoginForm() {
  return (
    <>
      <Head>
        <title>EcoEats</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
      className={style.topWrap}
      onClick={() => location.href = '/register'}
      >
        <img className={style.logo} src="/img/appLogo_wh.png" alt="logo" />
      </div>
    </>
  )
}
